insert into familiasp (nombre) values('Actividades Fisicas y Deportivas');
insert into familiasp (nombre) values('Administracion y Gestion');
insert into familiasp (nombre) values('Agraria');
insert into familiasp (nombre) values('Artes Graficas');
insert into familiasp (nombre) values('Comercio y Marketing');
insert into familiasp (nombre) values('Edificacion y Obra Civil');
insert into familiasp (nombre) values('Electricidad y Electronica');
insert into familiasp (nombre) values('Fabricacion Mecanica');
insert into familiasp (nombre) values('Hosteleria y Turismo');
insert into familiasp (nombre) values('Imagen Personal');
insert into familiasp (nombre) values('Industrias Alimentarias');
insert into familiasp (nombre) values('Informatica y Comunicaciones');
insert into familiasp (nombre) values('Instalacion y Mantenimiento');
insert into familiasp (nombre) values('Madera, Mueble y Corcho');
insert into familiasp (nombre) values('Maritimo-Pesquera');
insert into familiasp (nombre) values('Servicios Socioculturales y a la Comunidad');
insert into familiasp (nombre) values('Textil, Confeccion y Piel');
insert into familiasp (nombre) values('Transporte y Mantenimiento de Vehiculos');
insert into familiasp (nombre) values('Vidrio y Ceramica');
insert into familiasp (nombre) values('Energia y Agua');
insert into familiasp (nombre) values('Imagen y Sonido');
insert into familiasp (nombre) values('Industrias Extractivas');
insert into familiasp (nombre) values('Quimica');
insert into familiasp (nombre) values('Sanidad');
insert into familiasp (nombre) values('Seguridad y Medio Ambiente');
insert into familiasp (nombre) values('Artes y Artesanias');